Chinaza/pro 1483 prevent attestation document from going stale (#80)
* Added restart logic

* Add chrono dependency

* Added code to extract expiry time from attestation document

* Refactor

* print! -> println!

* Prevent edge-case

* Reuse tcp/vsock connection

* Restored logging

* Restore lockfile

* Fix compilation error in enclave code path

* Fix another enclave bug

* TimeZone was not in scope

* Added openssl::error::ErrorStack

* Need to convert from i64 to u64

* Pass through cargo fmt